version: '3'

services:
    php:
        build: docker/php/
        working_dir: /var/www/bot
        container_name: php
        restart: unless-stopped
        volumes:
            - ./:/var/www/bot
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-network
        depends_on:
            - nginx
            - mysql
    nginx:
        image: nginx:stable
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - ./:/var/www/bot
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network
    mysql:
        image: mysql:8.0
        container_name: mysql
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=bot
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local